### ISSUE TITLE
Version 3.1 not working in any version of Vegas Pro - Could not find render preset

### ISSUE THREAD

**Issue by DrZen33** [satishsampath/frame-server#55]
Hello
I have been using Debugmode Frameserver successfully for many years with Vegas Pro.
Using version 3.0, everything works in Vegas Pro 13, 14, 15, 16 and 17.
Before I tested v3.1, I re-tested v3.0 with Vegas Pro 17 and successfully frame-served to Handbrake 1.3.3.
This is the way I use Debugmode Frameserver - to ouput to Handbrake.

I uninstalled version 3.0 and installed version 3.1.
First I installed component **Magix Vegas Plugin - upto Vegas 17** and tested it with Vegas Pro 17.
It is not working now.
An error window opens and reports "Could not find the render preset defined by the script".
The command prompt window then goes into a infinite loop.....

Because you have changed something in Debugmode Frameserver 3.1, the script I was using is now broken.
I am guessing that an address in the script needs to be changed.
I am wondering if you would be able to find the line of code that needs to be changed and let me know what I have to do ?
I know I may be asking a lot, but would be extremely grateful if you could help out.
I have a lot of Vegas users who have upgraded to Vegas Pro 18, who are asking for help with this.

[fs2hb_en_04.zip](https://github.com/satishsampath/frame-server/files/5078003/fs2hb_en_04.zip)

When you open the files, I think the main file that needs to be fixed so it is compatible with DebugMode Frameserver 3.1, is located here:
fs2hb_en_04\fs2hb_en_04\frameserve_scripts\Send2HandBrake.js

Regards
Derek

**Comment by wwaag76** [comment]
I'm not the developer, but I can assure you that the problem is not with the new version.  You (or the author) will need to make changes to the Vegas2Handbrake script to make it compatible.  The new DMFS version now has options for different audio templates which is a major enhancement.  You will have to change the script to choose one of those options rather than the old selection which was simply "Project Default".  That's the reason for your error message.  Suggest you change it to "Audio: 48.0Khz, Video: project default".  Once you've done that, I suspect that it will work OK.  Or just use the old version with V17 if you want to use the Vegas2Handbrake.

**Comment by wwaag76** [comment]
Just downloaded the zip file that contains the js script.  Change line 13 as suggested above and try it.

**Comment by DrZen33** [comment]
Thanks @wwaag76 !!!!!!!!!!!!!!
I just did what you said and now it works OK!
Thank you so much for being helpful and very quick to reply.
Cheers :)
Derek

**Comment by satishsampath** [comment]
@DrZen33 do you mind informing the developer of the handbrake plugin as well? Thanks.
