### ISSUE TITLE
Setup file is flagged for malware/trojan

### ISSUE THREAD

**Issue by akaitori221** [satishsampath/frame-server#56]
https://www.virustotal.com/gui/file/b87ee267f9705a38f726a90ed959a0ae83c6f60755c61a5a4e2a801ac47b5b95/detection

What does this mean?

**Comment by satishsampath** [comment]
Did you get the frameserver installer from debugmode.com?

Since I created the installer myself in my machine, I believe it is safe. However, I also ran it by Kaspersky online and it said No Threats Detected https://opentip.kaspersky.com/B87EE267F9705A38F726A90ED959A0AE83C6F60755C61A5A4E2A801AC47B5B95/ .

From a personal perspective, I can assure you I didn't intentionally add any viruses :) but I should also run a full scan on my machine if you find any.

**Comment by akaitori221** [comment]
Hey Yes I did download the file from debugmode.com, you can go ahead and download it and put it through virustotal yourself

**Comment by satishsampath** [comment]
I've done it a month ago and also spoke with a virustotal representative. They can't fix it on their end as they are only an aggregator and pull data from multiple websites. So I've left it as is.
I'll close this issue as you downloaded it from debugmode.com and it's an installer I created on my machine, well checked for viruses already.
